alias bat='batcat'
alias ll='eza -l --git'
alias ls='eza -1'
alias l='ls -lah --group-directories-first --sort=modified'
alias gs='git status'
alias gpull='git pull'
alias :q='exit'
alias gpull='git pull'
alias ripgrep='rg'
alias c='clear'
alias nvim='~/Downloads/nvim-linux64/bin/nvim'
alias python='python3'
