alias ll='eza -l --git'
alias ls='eza -1'
alias l='ls -lah --group-directories-first --sort=modified'
alias gs='git status'
alias godot='~/Repos/Godot/./Godot.64'
alias gpull='git pull'
alias :q='exit'
alias gpull='git pull'
alias ripgrep='rg'
alias c='clear'
alias vpnup='bash ~/Repos/linux-files/scripts/wireguard/desktop/up_sweden.sh'
alias vpndown='bash ~/Repos/linux-files/scripts/wireguard/desktop/down_sweden.sh'
alias wgup='vpnup'
alias wgdown='vpndown'
alias wgstatus='bash ~/Repos/linux-files/scripts/wireguard/wireguard_status.sh'
alias razer='python3 ~/Repos/linux-files/scripts/razerlights.py'
